on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: cd client/ ; npm install

      - name: Generate build
        run: cd client/ ; npm run build

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cd client/ ; dist_*.zip"
          # bodyFile: "release.md"
          token: ${{ secrets.GITHUB_TOKEN }}
